language: perl

jobs:
  include:
    - name: focal-amd64a
      dist: focal
      group: dev
      os: linux
      perl: "5.33.0"
    - name: focal-amd64a
      dist: bionic
      os: linux
      perl: "5.33.0"

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y libgmp-dev
    - cpanm Test::Pod # optional dependency

script: "perl Build.PL; ./Build test"
